using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityStandardAssets.CrossPlatformInput;

public class ScenePause : MonoBehaviour {

    bool Pause = true;
    void Start()
    {

    }

    void Update()
    {

        if (Input.GetButtonDown("Cancel"))
        {
            Pause = !Pause;
            Time.timeScale = (Pause) ? 1.00f : 0.00f;
            if (Pause == false)
            {
                SceneManager.LoadScene("PauseE", LoadSceneMode.Additive);
            }
            else
            {
                SceneManager.UnloadSceneAsync("PauseE");
            }

        }
    }
}
